#!/home/fsw/.rbenv/shims/ruby

# TO_OUTPUT_ENABLE - Enables fsw <-> COSMOS communication
cmd("CFS TO_OUTPUT_ENABLE with CCSDS_STREAMID 6272, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 17, CCSDS_CHECKSUM 0, CCSDS_FC 6, DEST_IP '127.0.0.1'")

# CFS_WHE_POWER_SBC - Turn on power to circuit board
cmd("CFS CFS_WHE_POWER_SBC with CCSDS_STREAMID 6274, CCSDS_SEQUENCE 49152, CCSDS_LENGTH 1, CCSDS_CHECKSUM 0, CCSDS_FC 7")

